name: Build ClipShare Applications

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Build Windows executable
        run: |
          pyinstaller --onefile --icon=assets/clipshare.ico --name ClipShare-Windows --add-data "LICENSE;." windows_client.py
          
      - name: Package Windows application
        run: |
          mkdir -p release/windows
          copy dist\ClipShare-Windows.exe release\windows\
          copy README.md release\windows\
          copy LICENSE release\windows\
          
      - name: Upload Windows build
        uses: actions/upload-artifact@v3
        with:
          name: clipshare-windows
          path: release/windows/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Build macOS application
        run: |
          pyinstaller --onefile --icon=assets/clipshare.icns --name ClipShare-Mac --add-data "LICENSE:." mac_clip_check.py
          
      - name: Package macOS application
        run: |
          mkdir -p release/macos
          cp dist/ClipShare-Mac release/macos/
          cp README.md release/macos/
          cp LICENSE release/macos/
          chmod +x release/macos/ClipShare-Mac
          
      - name: Upload macOS build
        uses: actions/upload-artifact@v3
        with:
          name: clipshare-macos
          path: release/macos/

  create-release:
    needs: [build-windows, build-macos]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: clipshare-windows
          path: release/windows
          
      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: clipshare-macos
          path: release/macos
          
      - name: Create ZIP archives
        run: |
          cd release
          zip -r clipshare-windows.zip windows
          zip -r clipshare-macos.zip macos
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/clipshare-windows.zip
            release/clipshare-macos.zip
          draft: false
          prerelease: false
